main.name = "pi5"
main.lang = "en"
main.whitelist = [
 "urnetwork",
 "ANOTHER_EXAMPLE_NETWORK",
 "fo:od:ba:be:fo:od",
 "fo:od:ba",
]
main.plugins.grid.enabled = false
main.plugins.grid.report = false
main.plugins.grid.exclude = [ "urnetwork",]

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = false
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.mac = ""
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.interval = 1
main.plugins.bt-tether.devices.android-phone.scantime = 15
main.plugins.bt-tether.devices.android-phone.max_tries = 6
main.plugins.bt-tether.devices.android-phone.share_internet = false
main.plugins.bt-tether.devices.android-phone.priority = 1

main.plugins.bt-tether.devices.ios-phone.enabled = false
main.plugins.bt-tether.devices.ios-phone.search_order = 1
main.plugins.bt-tether.devices.ios-phone.mac = ""
main.plugins.bt-tether.devices.ios-phone.ip = "172.20.10.6"
main.plugins.bt-tether.devices.ios-phone.netmask = 24
main.plugins.bt-tether.devices.ios-phone.interval = 1
main.plugins.bt-tether.devices.ios-phone.scantime = 10
main.plugins.bt-tether.devices.ios-phone.max_tries = 10
main.plugins.bt-tether.devices.ios-phone.share_internet = false
main.plugins.bt-tether.devices.ios-phone.priority = 1

main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.enabled = false
main.plugins.gdrivesync.backupfiles = [ "",]
main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"

main.plugins.logtail.enabled = true
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = false
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.session-stats.enabled = true
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.webcfg.enabled = true

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "addkey" 
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = true

main.plugins.wpa-sec-list.enabled = true

main.plugins.gps.enabled = true
main.plugins.gps.speed = 9600
main.plugins.gps.device = "/dev/ttyACM0"

main.plugins.gps_sat.enabled = true
main.plugins.gps_sat.position = "127,83"

main.plugins.webgpsmap.enabled = true

main.plugins.wigle.enabled = false
main.plugins.wigle.api_key = ""
main.plugins.wigle.donate = false


main.plugins.IPDisplay.enabled = true
main.plugins.IPDisplay.skip_devices = [ "lo",]

main.plugins.tweak_view.enabled = true

main.plugins.exp.enabled = true
main.plugins.exp.lvl_x_coord = 156
main.plugins.exp.lvl_y_coord = 72
main.plugins.exp.exp_x_coord = 196
main.plugins.exp.exp_y_coord = 72
main.plugins.exp.bar_symbols_count = 8

main.plugins.enable_deauth.enabled = false

main.plugins.enable_assoc.enabled = true

main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugin_repos = [
 "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
 "https://github.com/tisboyo/pwnagotchi-pisugar2-plugin/archive/master.zip",
 "https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3/archive/master.zip",
 "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
 "https://github.com/NeonLightning/pwny/archive/master.zip",
 "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
]
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.plugin.gdrivesync.interval = 1

main.iface = "wlan0mon"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 50
main.no_restart = false
main.log.path = "/etc/pwnagotchi/log/pwnagotchi.log"
main.log.rotation.enabled = true
main.log.rotation.size = "50M"

ui.display.enabled = true
ui.display.type = "waveshare_4"
ui.display.color = "black"
ui.display.rotation = 180

ui.invert = false
ui.fps = 10
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0

ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_l = "(☉_⚆)"
ui.faces.look_r_happy = "( ʘ‿ʘ)"
ui.faces.look_l_happy = "(ʘ‿ʘ )"
ui.faces.sleep = "(╯︵╰)"
ui.faces.sleep2 = "(≖︿≖)"
ui.faces.awake = "(◉◡◉)"
ui.faces.bored = "(⌾_⌾)"
ui.faces.intense = "(⊚▃⊚)"
ui.faces.cool = "(⌐■_■)"   
ui.faces.happy = "(≧◡≦)"
ui.faces.excited = "(ʘ‿ʘﾉ)"
ui.faces.grateful = "(^人^)"
ui.faces.motivated = "(✧◡✧)"
ui.faces.demotivated = "(⌾︿⌾)"
ui.faces.smart = "(✪‿✪)"
ui.faces.lonely = "(ب__ب)"
ui.faces.sad = "(╥☁╥ )"
ui.faces.angry = "(>︵<)"
ui.faces.friend = "(♥‿♥)"
ui.faces.broken = "(✖︿✖)"
ui.faces.debug = "(⌾_⌾)"
ui.faces.upload = "(↑↗)"
ui.faces.upload1 = "(↑↓)"
ui.faces.upload2 = "(↓↑)"
ui.faces.png = false
ui.faces.position_x = 0
ui.faces.position_y = 34


ui.web.enabled = true
ui.web.address = "::"
ui.web.username = "pi5"
ui.web.password = "pi5"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = ""

ai.enabled = true
ai.path = "/root/brain.nn"
ai.laziness = 0.0004
ai.epochs_per_episode = 100
ai.params.gamma = 0.98
ai.params.n_steps = 5
ai.params.vf_coef = 0.3
ai.params.ent_coef = 0.02
ai.params.max_grad_norm = 1.0
ai.params.learning_rate = 0.000005
ai.params.verbose = 1

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161, 165
]
personality.min_rssi = -130
personality.ap_ttl = 300
personality.sta_ttl = 250
personality.recon_time = 40
personality.max_inactive_scale = 6
personality.recon_inactive_multiplier = 1.2
personality.hop_recon_time = 25
personality.min_recon_time = 1
personality.max_interactions = 10
personality.max_misses_for_recon = 4
personality.excited_num_epochs = 15
personality.bored_num_epochs = 22
personality.sad_num_epochs = 25
personality.bond_encounters_factor = 25000
personality.throttle_a = 0.3
personality.throttle_d = 0.85
personality.clear_on_exit = true

bettercap.handshakes = "/home/pi/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/etc/pwnagotchi/log/"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "20M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
fs.memory.mounts.data.rsync = true

